IODT/attendance/urls.py
from django.contrib import admin
from django.urls import include, path
from register.views import my_login, my_profile, tracking_test
from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from donations import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reports.urls')),
    path('register/', include('register.urls')),
    path('management/', include('management.urls')),
    path('donations/', include('donations.urls')),
    path('login/', my_login, name='login'),
    path('profile/', my_profile, name='profile'),
    path('tracking_test/', tracking_test, name='tracking_test'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IODT/reports/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('project/<int:project_id>/', views.project_view, name='project_view'),
    path('project/manage/<int:project_id>/', views.project_management, name='project_management'),
    # path('login/', views.login, name='login'),

    path('api/project_summary/<int:project_id>/', views.project_summary_api.as_view(), name='project_summary_api'),
    path('api/change_status/', views.change_status, name='change_status'),
]

IODT/donations/models.py
from django.urls import reverse

# Create your models here.
from django.db import models
from django.db.models.deletion import SET_NULL
from django.db.models.fields import DateTimeField
from django.db.models.fields.related import ForeignKey
# from django.contrib.gis.db import models

from datetime import datetime 
from register.models import Doner, Recipient


# from management.models import ClassRoom, Student
class Location(models.Model):
    TYPES = (
        ('feedback', 'การตอบกลับ'),
        ('shipping', 'การขนส่ง'),
        ('update', 'การอัปเดต')
    )
    name = models.CharField(max_length=40, blank=True)
    _type = models.CharField(max_length=10,choices=TYPES, default='update')
    ladtitude = models.CharField(max_length=50)
    longtitude = models.CharField(max_length=50)
    def __str__(self):
        return 'ladtitude : '+self.ladtitude+' longtitude : '+ self.longtitude
    
class RequireType(models.Model):
    name = models.CharField(max_length=30)
    desc = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
class Album(models.Model):
    name = models.CharField(max_length=30,blank=True)
    desc = models.CharField(max_length=255,blank=True)

class Project(models.Model):
    STATUS = (
        ('open','เปิดรับริจาค'),
        ('close', 'ปิดรับบริจาค'),
        ('process', 'ดำเนินการ'),
        ('finished', 'เสร็จสิ้น')
    )
    name = models.CharField(max_length=50)
    desc = models.TextField()
    requiretype = models.ManyToManyField(RequireType)
    propose = models.CharField(max_length=255)
    helping_people = models.SmallIntegerField()
    address = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    create_date = models.DateField(auto_now_add=True)
    expire_date = models.DateTimeField()
    recipient = models.ForeignKey(Recipient, on_delete=models.SET_NULL, null=True)
    album = models.OneToOneField(Album, on_delete=models.CASCADE, null=True)

    # def amount_donation(self):

class Picture(models.Model):
    name = models.CharField(max_length=30, blank=True)
    url = models.ImageField(upload_to='album/pic/')
    album = models.ForeignKey(Album, on_delete=models.CASCADE, default=0)

class Donation(models.Model):
    STATUS = (
        ('Yet', 'ยังไม่บริจาค'),
        ('Pending','รอการยืนยัน'),
        ('Recieve','ได้รับของบริจาค')
    )
    CONDITION = (
        ('1','ชำรุด'),
        ('2','ต้องซ่อม'),
        ('3','ดี'),
        ('4','เสมือนใหม่'),
        ('5','ใหม่'),
    )
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=20, choices=STATUS, default=STATUS[0][0])
    dtype = models.ForeignKey(RequireType, null=True, on_delete=SET_NULL)
    desc = models.TextField()
    condition = models.CharField(max_length=1, choices=CONDITION)
    quantity = models.IntegerField(default=1)
    date = models.DateField(auto_now=True)
    donor = models.ForeignKey(Doner, on_delete=models.CASCADE, default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True)
    album = models.OneToOneField(Album, on_delete=models.CASCADE, null=True)

from io import BytesIO
import base64
import pyqrcode

class Qrcode(models.Model):
    donation = models.OneToOneField(Donation, on_delete=models.CASCADE, null=True)
    use_flag = models.BooleanField(default=False)
    value = models.CharField(max_length=32, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

class SendDetail(models.Model):
    METHOD = (
        ('EMS','ส่งทางไปรษณีย์'),('SELF','ไปส่งที่ผุ้รับด้วยตัวเอง'),('TAKEHOME','ผุ้รับมารับ'),('TRANFER','โอนเงิน')
    )
    _type = models.CharField(max_length=8, choices=METHOD)

class Shipping(models.Model):
    S_COMPANY = (
        ('THAIPOST', 'ไปรษณีย์ไทย'),
        ('KERRY','เคอรรี่'),
        ('FLASH', 'เเฟลช')
    )
    tracking_id = models.CharField(max_length=50)
    company = models.CharField(choices=S_COMPANY,max_length=8)
    reciept = models.ImageField(upload_to='shipping/slip/')
    send_datetime = models.DateTimeField()
    senddetail = models.OneToOneField(SendDetail, on_delete=models.CASCADE, default=0)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, default=0)

class Feedback(models.Model):
    sender = models.ForeignKey(Recipient, on_delete=models.SET_NULL, null=True)
    header = models.CharField(max_length=40)
    detail = models.TextField()
    sent_date = models.DateTimeField(auto_now_add=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE, default=0)
    album = models.OneToOneField(Album, on_delete=models.SET_NULL, null=True)

IODT/reports/models.py
from django.db import models

# Create your models here.

IODT/reports/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from donations.models import Project, Donation, Album, Picture
from register.forms import regForm
from register.models import Organization
from django.contrib.auth.decorators import login_required

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from donations.serializers import ProjectSummarySerializer

import json

# Create your views here.

def dashboard(request):
    return render(request, 'report/report.html')

def search(request):
    return HttpResponse('Attendance Search Page.')

def index(request):
    context = {}
    user = request.user
    if user.is_authenticated:
        context[user] = request.user
    context['form'] = regForm()
    return render(request, 'report/index_2.html', context)

def project_view(request, project_id):
    contexts = {}
    project = Project.objects.get(pk=project_id)
    project_picture = Picture.objects.filter(album=project.album)
    donation_in_project = Donation.objects.filter(project=project)
    contexts['project'] = project
    contexts['project_picture'] = project_picture
    contexts['project_in_project'] = donation_in_project
    return render(request, 'report/project_view.html',context=contexts)

@login_required
def project_management(request, project_id):
    contexts = {}
    project = Project.objects.get(pk=project_id)
    project_picture = Picture.objects.filter(album=project.album)
    donation_in_project = Donation.objects.filter(project=project)
    contexts['project'] = project
    contexts['project_picture'] = project_picture
    contexts['project_in_project'] = donation_in_project
    return render(request, 'report/project_management.html',context=contexts)

class project_summary_api(APIView):
    """ API ดึงข้อมูลสรุปทั้งหมดของ ของโปรเจค โดย รับ Project_id ทาง path 
        สามารถ patch สถานะโครงการได้"""
    def get(self, request, project_id):
        """ ส่งข้อมูลสรุปไป """
        project = Project.objects.get(id=project_id)
        print(project)
        serializer = ProjectSummarySerializer(project)
        return Response(serializer.data, status=status.HTTP_200_OK)

def change_status(request):
    if request.method == 'PATCH':
    # """project_id, status"""
        data = json.loads(request.body)
        project = Project.objects.get(pk=int(data['project_id']))
        project.status = data['status']
        project.save()
        print(project)
        serializer = ProjectSummarySerializer(project)
        return JsonResponse(serializer.data, status=status.HTTP_200_OK)
    return HttpResponse(status=405)

IODT/reports/templates/report/index.html
{% extends "base3.html" %}
{% load static %}
{% block content %}

      <br><br>
      <div class="container">
        <div class="row">
            <h1 class="h1 mx-auto">ค้นหาความช่วยเหลือ</h1>
        </div>
        

        <div class="row justify-content-md-center">

            
            <div class="col col-lg-4" style="padding: 5px;">
                

                <select class="custom-select custom-select-lg">
                    <option selected>สิ่งของที่ต้องการบริจาค</option>
                    <option value="1">อาหาร</option>
                    <option value="2">หนังสือ</option>
                    <option value="3">เครื่องแต่งกาย</option>
                    <option value="4">ทุนการศึกษา</option>
                </select>
                  

            </div>
            <div class="col-lg-3" style="padding: 5px;">
              

                <select class="custom-select custom-select-lg">
                    <option selected>มูลนิธิ</option>
                    <option value="1">เด็กกำพร้า</option>
                    <option value="2">ผู้พิการ</option>
                    <option value="3">บ้านพักคนชรา</option>
                    <option value="4">ผู้ป่วย</option>
                </select>


            </div>
            <div class="col col-lg-2" style="padding: 5px;">

                <select class="custom-select custom-select-lg">
                    <option selected>จังหวัด</option>
                    <option value="1">กรุงเทพมหานคร</option>
                    <option value="2">เชียงใหม่</option>
                    <option value="3">ชลบุรี</option>
                    <option value="4">....</option>
                </select>
                
            </div>



            <div class="col-md-auto" style="padding: 5px;">
                <button class="btn btn-primary btn-lg btn-block">ค้นหา</button>
            </div>


          </div>


          




          <br><br>

          <div class="row">
            <div class="col-lg-6" style="padding: 5px;">

                <div class="card text-white">
                  
                    <img src="https://77kaoded.com/wp-content/uploads/2018/03/D1.jpg" class="card-img" alt="...">
                    
                    <div class="card-img-overlay" style="padding:0;">
                      
                      <p class="card-text h5" style="padding: 10px;box-shadow: inset 0 50px 25px -5px rgba(0,0,0,0.5);height: 30%;">บ้านเด็กกำพร้า</p>
                      
                    </div>
                  </div>

            </div>
            <div class="col-lg-6" style="padding: 5px;">

                <div class="card text-white">
                    <img src="https://i.ytimg.com/vi/oljdxf4zd0o/maxresdefault.jpg" class="card-img" alt="...">
                    <div class="card-img-overlay" style="padding:0;">
                      
                      <p class="card-text h5" style="padding: 10px;box-shadow: inset 0 50px 25px -5px rgba(0,0,0,0.5);height: 30%;">บ้านเด็กกำพร้า</p>
                    
                    </div>
                  </div>

            </div>
            <div class="col-lg-4" style="padding: 5px;">

                <div class="card text-white">
                    <img src="https://77kaoded.com/wp-content/uploads/2018/03/D1.jpg" class="card-img" alt="...">
                    <div class="card-img-overlay" style="padding:0;">
                      
                        <p class="card-text h5" style="padding: 10px;box-shadow: inset 0 50px 25px -5px rgba(0,0,0,0.5);height: 30%;">บ้านเด็กกำพร้า</p>
                      
                    </div>
                  </div>

            </div>
            <div class="col-lg-4" style="padding: 5px;">

                <div class="card text-white">
                    <img src="https://77kaoded.com/wp-content/uploads/2018/03/D1.jpg" class="card-img" alt="...">
                    <div class="card-img-overlay" style="padding:0;">
                      
                        <p class="card-text h5" style="padding: 10px;box-shadow: inset 0 50px 25px -5px rgba(0,0,0,0.5);height: 30%;">บ้านเด็กกำพร้า</p>
                      
                    </div>
                  </div>

            </div>
            <div class="col-lg-4" style="padding: 5px;">

                <div class="card text-white">
                    <img src="https://77kaoded.com/wp-content/uploads/2018/03/D1.jpg" class="card-img" alt="...">
                    <div class="card-img-overlay" style="padding:0;">
                      
                        <p class="card-text h5" style="padding: 10px;box-shadow: inset 0 50px 25px -5px rgba(0,0,0,0.5);height: 30%;">บ้านเด็กกำพร้า</p>
                      
                    </div>
                  </div>

            </div>
          </div>




          <br>
          <br>
          <div class="row">
            <h1 class="h1 mx-auto">การร้องขอล่าสุด</h1>
        </div>





      </div>
{% endblock content %}

IODT/reports/templates/report/project_management.html
{% extends "base3.html" %}
{% block Scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
{% endblock Scripts %}
{% block content %}
{% load static %}
<style>
    .dashboard {
        width: 100%;
        height: 6em;
    }

    .num_dashboard {
        font-size: 3em;
    }

    .active {
        background-color: rgb(255, 127, 202) !important;
    }
</style>
<div class="container" id='app'>
    <div class="row">
        <div class="col-10">
            {% include "messages.html" %}
        </div>
    </div>
    <div class="row justify-content-start">
        <div class="col-md-6 mb-3">
            <div class="card w-20">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for pic in project_picture %}
                        {% if forloop.first %}
                        <div class="carousel-item active">
                            <img src="/media/{{ pic.url }}" class="d-block " alt="{{pic.name}}" style=" object-fit: cover;
                        object-position: 0 0;
                        width: 100%;
                        height: 337px;">
                        </div>
                        {% else %}
                        <div class="carousel-item">
                            <img src="/media/{{ pic.url }}" class="d-block " alt="{{pic.name}}" style=" object-fit: cover;
                        object-position: 0 0;
                        width: 100%;
                        height: 337px;">
                        </div>
                        {% endif %}
                        {% endfor %}

                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="card-body">
                    <h5 class="card-title">โครงการ : {{project.name}}</h5>
                    <p class="card-text">คำอธิบาย : {{project.desc}}</p>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">ผู้ดูเเลโครงการ : {{project.recipient}}</li>
                        <li class="list-group-item">จุดประสงค์ : {{project.propose}}</li>
                        <li class="list-group-item">จำนวนที่จะไปช่วย : {{project.helping_people}} คน</li>
                        <li class="list-group-item">ที่ {{project.address}}</li>
                    </ul>
                    <p class="card-text"><small class="text-muted">ปิดรับบริจาควันที่ {{project.expire_date}}</small>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-2">
            <div class="card w-40">
                <div class="card-body">

                    <h1 class="card-header">สรุปโครงการ</h1>
                    <div class="row justify-content-between mx-4 my-4">
                        <div class="dashboard bg-success col-3">ยืนยันเเล้ว <div class="num_dashboard">[[
                                project_summary.status_donation.Recieve ]]</div>
                        </div>
                        <div class="dashboard bg-warning col-3">รอการยืนยัน <div class="num_dashboard">[[
                                project_summary.status_donation.Pending ]]</div>
                        </div>
                        <div class="dashboard bg-danger col-3">ต้องการ <div class="num_dashboard">[[
                                project_summary.status_donation.All ]]</div>
                        </div>
                    </div>
                    <h5 class="card-header">สิ้นสุดโครงการใน : [[ project_summary.expire_duration.day ]] วัน [[
                        project_summary.expire_duration.hour]] ชั่วโมง [[project_summary.expire_duration.min]] นาที</h5>
                    <div class="row justify-content-center">
                        <canvas id="pie-chart" width="800" height="450"></canvas>
                    </div>
                    <div class="row justify-content-center my-5">
                        <!-- <div class="btn-group btn-group-justified">
                            <a href="#" class="btn btn-success">เปิดรับบริจาค</a>
                            <a href="#" class="btn btn-secondary">ปิดรับบริจาค</a>
                            <a href="#" class="btn btn-secondary">ดำเนินการ</a>
                            <a href="#" class="btn btn-secondary">เสร็จสิ้น</a>
                        </div> -->
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            <label id='open' class="btn btn-secondary">
                                <input type="radio" name="options" id="option1" v-on:click='change_status("open")'>
                                เปิดรับบริจาค
                            </label>
                            <label id='close' class="btn btn-secondary">
                                <input type="radio" name="options" id="option2" v-on:click='change_status("close")'>
                                ปิดรับบริจาค
                            </label>
                            <label id='process' class="btn btn-secondary">
                                <input type="radio" name="options" id="option3" v-on:click='change_status("process")'>
                                ดำเนินการ
                            </label>
                            <label id='finished' class="btn btn-secondary">
                                <input type="radio" name="options" id="option3" v-on:click='change_status("finished")'>
                                เสร็จสิ้น
                            </label>
                        </div>
                    </div>




                </div>
            </div>
        </div>

    </div>

    <div class="row">

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ลำดับ</th>
                    <th scope="col">วันที่ลงทะเบียน</th>
                    <th scope="col">ชื่อ</th>
                    <th scope="col">ประเภท</th>
                    <th scope="col">สภาพ</th>
                    <th scope="col">จำนวน</th>
                    <th scope="col">สถานะ</th>
                    <th scope="col"></th>


                </tr>
            </thead>
            <tbody>
                {% for donation in project_in_project %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{donation.date}}</td>
                    <td>{{donation.name}}</td>
                    <td>{{donation.dtype.name}}</td>
                    <td>{{donation.get_condition_display}}</td>
                    <td>{{donation.quantity}}</td>
                    <td>{{donation.get_status_display}}</td>
                    <td>
                        <a class="btn btn-secondary btn-sm" href="{% url 'tracking' donation.id %}">รายละเอียด</a>
                        <a 
                            class="btn btn-success btn-sm" href="{% url 'confirm_donation' donation_id=donation.id status='Recieve' %}">ยืนยัน</a>
                        </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken'
    axios.defaults.xsrfHeaderName = 'X-CSRFTOKEN'
    var app = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        data: {
            project_summary: [],
            data: [],
            status: ''
        },
        methods: {
            get_project_summary: function () {
                let self = this
                axios.get('/api/project_summary/{{ project.id }}/', {
                    params: {
                    }
                })
                    .then(function (response) {
                        console.log(response);
                        app.project_summary = response.data;
                        app.data = [app.project_summary.condition_count.broke, app.project_summary.condition_count.fix, app.project_summary.condition_count.standard, app.project_summary.condition_count.good, app.project_summary.condition_count.best]
                        app.status = app.project_summary.status

                    })
                    .catch(function (error) {
                        console.log(error);
                    });

            },
            change_status: function (status) {
                if (confirm("คุณต้องการเปลี่ยนสถานะโครงการ?")) {
                    let self = this
                    axios.patch('/api/change_status/', {
                        project_id: '{{ project.id }}',
                        status: status
                    })
                        .then(function (response) {
                            console.log(response);
                            app.project_summary = response.data;
                            app.update_status()
                        })
                        .catch(function (error) {
                            console.log(error);
                        });
                } 
            }, update_status: function () {

                // if (app.status == "finished") {
                //     var element = document.getElementById('finished')
                //     element.classList.add("active");
                // }
                // else if (app.status == 'close') {

                //     var element = document.getElementById('close')
                //     element.classList.add("active");
                // }
                // else if (app.status == 'process') {

                //     var element = document.getElementById('process')
                //     element.classList.add("active");
                // }
                // else if (app.status == 'open') {
                //     var element = document.getElementById('open')
                //     element.classList.add("active");
                // }
            }
        }, created() {
            this.get_project_summary()


        }
    })
    setTimeout(create_pie, 500);
    function create_pie() {

        new Chart(document.getElementById("pie-chart"), {
            type: 'pie',
            data: {
                labels: ["ชำรุด", "ต้องซ่อม", "ดี", "เสมือนใหม่", "ใหม่"],
                datasets: [{
                    label: "สภาพสิ่งของบริจาค",
                    backgroundColor: ["#3e95cd", "#8e5ea2", "#3cba9f", "#e8c3b9", "#c45850"],
                    data: app.data
                }]
            },
            options: {
                title: {
                    display: true,
                    text: 'สภาพสิ่งของบริจาคโดยรวม'
                }
            }
        });
    }
</script>


{% endblock content %}

IODT/reports/templates/report/project_view.html
{% extends "base3.html" %}

{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-10">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
    <div class="row">
    </div>
    <div class="row">
        <div class="card mb-3">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for pic in project_picture %}
                    {% if forloop.first %}
                    <div class="carousel-item active">
                        <img src="/media/{{ pic.url }}" class="d-block " alt="{{pic.name}}" style="height: 576px; width: 70vw;">
                    </div>
                    {% else %}
                    <div class="carousel-item">
                        <img src="/media/{{ pic.url }}" class="d-block " alt="{{pic.name}}" style="height: 576px; width: 70vw;">
                    </div>
                    {% endif %}
                    {% endfor %}
    
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="card-body">
              <h5 class="card-title">โครงการ : {{project.name}}</h5>
              <p class="card-text">คำอธิบาย : {{project.desc}}</p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">ผู้ดูเเลโครงการ : {{project.recipient}}</li>
                <li class="list-group-item">จุดประสงค์ : {{project.propose}}</li>
                <li class="list-group-item">จำนวนที่จะไปช่วย : {{project.helping_people}} คน</li>
                <li class="list-group-item">ที่ {{project.address}}</li>
              </ul>
              <p class="card-text"><small class="text-muted">ปิดรับบริจาควันที่ {{project.expire_date}}</small></p>
            </div>
          </div>
    </div>

    <div class="row">

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ลำดับ</th>
                    <th scope="col">วันที่ลงทะเบียน</th>
                    <th scope="col">ชื่อ</th>
                    <th scope="col">ประเภท</th>
                    <th scope="col">สภาพ</th>
                    <th scope="col">จำนวน</th>
                    <th scope="col">สถานะ</th>


                </tr>
            </thead>
            <tbody>
                {% for donation in project_in_project %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{donation.date}}</td>
                    <td>{{donation.name}}</td>
                    <td>{{donation.dtype.name}}</td>
                    <td>{{donation.get_condition_display}}</td>
                    <td>{{donation.quantity}}</td>
                    <td>{{donation.get_status_display}}</td>
 
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}

IODT/reports/templates/report/report.html
{% extends "base3.html" %}
{% block content %}
    <div class="container">
        <h1>Your Donations Things</h1>
        <p></p>
        <br/><br/>
        <!-- <form class="form-inline" method="GET" action="{% url 'index' %}">
            <div class="form-group">
                <label for="inputSearch">filter:</label>
                <input type="text" class="form-control ml-3" id="inputSearch" 
                    name="inputSearch" placeholder="Search" value="{{search_txt}}">
            </div>
            <button type="submit" class="btn btn-primary ml-3">Submit</button>
        </form> -->
        <br/><br/>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">สิ่งที่บริจาค</th>
                    <th scope="col">รหัส</th>
                    <th scope="col">ชื่อโครงการ</th>
                    <th scope="col">มอบให้</th>
                    <th scope="col">สถานะ</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for cl in classes %}
                <tr>
                    <td>{{ cl.weekday }} @ {{ cl.time }}</td>
                    <td>{{ cl.course.name }} ({{ cl.course.code }})</td>
                    <td>{{ cl.section }}</td>
                    <td>{{ cl.room }}</td>
                    <td>{{ cl.student_amount }}</td>
                    <td>
                        <a href="{% url 'class_detail' class_id=cl.id %}">
                            <div class="btn btn-warning" id="{{cl.id}}">ผลตอบรับ</div>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block footer %}
    Footer of index page!!!
{% endblock %}